#!/bin/bash

GITFOLDER=eclipse
ECLIPSEFOLDER=/Users/joshangelsberg/Documents/CS122b/tomcat/FabFlix

if [ -d "eclipse" ]; then
  rm -rf $GITFOLDER
fi

mkdir $GITFOLDER
mkdir $GITFOLDER/src
mkdir $GITFOLDER/src/model
mkdir $GITFOLDER/src/servlets
mkdir $GITFOLDER/WebContent

cp -R $ECLIPSEFOLDER/WebContent/ $GITFOLDER/WebContent/
cp -R $ECLIPSEFOLDER/src/model/ $GITFOLDER/src/model/
cp -R $ECLIPSEFOLDER/src/servlets/ $GITFOLDER/src/servlets/

rm -rf $GITFOLDER/src/model/Credentials.java