#!/bin/bash

GITFOLDER=eclipse
ECLIPSEFOLDER=../../Session

if [ -d "eclipse" ]; then
  rm -rf $GITFOLDER
fi

mkdir $GITFOLDER
mkdir $GITFOLDER/src
mkdir $GITFOLDER/src/tester
mkdir $GITFOLDER/WebContent

cp -R $ECLIPSEFOLDER/WebContent/ $GITFOLDER/WebContent/
cp -R $ECLIPSEFOLDER/src/tester/ $GITFOLDER/src/tester/

rm -rf $GITFOLDER/src/tester/Credentials.java

echo $GITFOLDER/src/tester
ls $GITFOLDER/src/tester/

echo $GITFOLDER/WebContent
ls $GITFOLDER/WebContent