#!/bin/bash

GITFOLDER=eclipse
ECLIPSEFOLDER=../../Session

if [ -d "eclipse" ]; then
	mkdir $ECLIPSEFOLDER/src/tmp/
	mv $ECLIPSEFOLDER/src/tester/Credentials.java $ECLIPSEFOLDER/src/tmp/Credentials.java
	rm -rf $ECLIPSEFOLDER/WebContent/
	rm -rf $ECLIPSEFOLDER/src/tester/
	mkdir $ECLIPSEFOLDER/WebContent/
	mkdir -rf $ECLIPSEFOLDER/src/tester/
  	cp -R $GITFOLDER/WebContent/ $ECLIPSEFOLDER/WebContent/
  	cp -R $GITFOLDER/src/tester/ $ECLIPSEFOLDER/src/tester/
  	mv $ECLIPSEFOLDER/src/tmp/Credentials.java $ECLIPSEFOLDER/src/tester/Credentials.java
  	rm -rf $ECLIPSEFOLDER/src/tmp/
fi

echo $ECLIPSEFOLDER/WebContent/
ls $ECLIPSEFOLDER/WebContent/

echo $ECLIPSEFOLDER/src/tester/
ls $ECLIPSEFOLDER/src/tester/