#!/bin/bash

GITFOLDER=eclipse
ECLIPSEFOLDER=../FabFlix

if [ -d "eclipse" ]; then
	mkdir $ECLIPSEFOLDER/src/tmp/
	
	if [ -e "$ECLIPSEFOLDER/src/model/Credentials.java" ]; then
		mv $ECLIPSEFOLDER/src/model/Credentials.java $ECLIPSEFOLDER/src/tmp/Credentials.java
	fi

	rm -rf $ECLIPSEFOLDER/WebContent/
	rm -rf $ECLIPSEFOLDER/src/model/
	rm -rf $ECLIPSEFOLDER/src/servlets/

	mkdir $ECLIPSEFOLDER/WebContent/
	mkdir $ECLIPSEFOLDER/src/model/
	mkdir $ECLIPSEFOLDER/src/servlets/

  	cp -R $GITFOLDER/WebContent/ $ECLIPSEFOLDER/WebContent/
  	cp -R $GITFOLDER/src/model/ $ECLIPSEFOLDER/src/model/
  	cp -R $GITFOLDER/src/servlets/ $ECLIPSEFOLDER/src/servlets/

  	if [ -e "$ECLIPSEFOLDER/src/tmp/Credentials.java" ]; then
		mv $ECLIPSEFOLDER/src/tmp/Credentials.java $ECLIPSEFOLDER/src/model/Credentials.java
	fi

  	rm -rf $ECLIPSEFOLDER/src/tmp/
fi